# Generated by Django 2.1.4 on 2018-12-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
